
service: default
runtime: python37

env_variables:
    FLASK_APP: 'main:app'
    FLASK_ENV: 'production'

instance_class: F1

# ./cloud_sql_proxy -instances=sicho-272801:us-west2:sicho-itson=tcp:3306
